dist: bionic
addons:
 apt:
  packages: [doxygen, graphviz]
language: python
python:
  - "3.7"

sudo: false
cache:
  directories:
    - "~/.platformio"

install:
  - pip3 install --upgrade pip
  - pip3 install setuptools
  - pip3 install Sphinx
  - pip3 install platformio
  - platformio update

script:
  - make -C test
  - make -C docs html linkcheck
  - git diff --exit-code

notifications:
  email:
    recipients:
      - secure: "Vyn0ToMRejcne8dBXcaDUOdTb2WJswtxq+Og2/DzkcJDelJ/QfQj+sQCfoiqXp4ZDk8zlkhW396OD8ZnWqxEBIP7SX1b2SDotmWe3h5Jw4azfbbg6Z3plnmej/yQFUq7ao4lR92OJSQX6z+zJ4C3kqTZsK9c/pzAHwlCcW8a67/nK38Tcy/eHb1Z0P38l2LkuLWDVSMb9vM24Wmt+Jl6JXOabZrR0/sqEnRIxunGywzl89oKDu/4ZqeKUKtvj/+bf8uEgD0LoErGornvFOge6z0vEzRc4szpPEcGEI2+1cHGu5QzDUREDKSKclMaK99yGBtNDCBl0hsLuhSTbKdHilU7/7B9bdnbdNp5o76Xk6mMOKur1zBU2MC1cs8FlZPvEONHO5JQKVF/EzjmTV8eV14jotAI7cmUx/hLHaB58EjDcxJsCqIFyyZs9cwjNv6obqQOU1pL6zQ5VUE6MM53oS4CjAAxlqd96on9JCPbhfpkQZx3akARstPKUIQ2R6zluO0hyGaMuCn+gpZEMJ9iI0Yzl5lTEYEyzzn+1jbHUiuYFpAkacRsjPLT8At4L9MXA5nzhOAvXYi+wVD9qErvkxm3/PSsODt+p3bEBbYqGQtf9J6raORVgDzauwJ4Lc6LF28sBxy+9ZEW0X+08HbIb0aWV4+nO40OeLvF+nSS+Lk="
